import os

from constants import RECOGNIZER_WIT

# RECOGNITION_ENGINE = RECOGNIZER_SNOWBOY
# RECOGNITION_ENGINE = RECOGNIZER_SPHINX
RECOGNITION_ENGINE = RECOGNIZER_WIT


WIT_AI_KEY = os.environ.get('WIT_ACCESS_TOKEN')


